// Author: Antoine Mercadal
// See LICENSE file for full LICENSE
// Copyright 2016 Aporeto.

package bahamut

import (
	"crypto/tls"
	"crypto/x509"
	"time"

	"github.com/aporeto-inc/elemental"
)

// An APIServerConfig represents the configuration for the APIServer.
type APIServerConfig struct {

	// EnableProfiling defines if the profiling server should
	// be created. You should only use this when debugging.
	EnableProfiling bool

	// ProfilingListenAddress is the custom listening address to use.
	// It will be only used if EnableProfiling is set to true.
	ProfilingListenAddress string

	// ListenAddress is the general listening address for the API server as
	// well as the PushServer.
	ListenAddress string

	// Routes holds all the routes Bahamut will serve. Those routes
	// Are normally autogenerated from specifications.
	Routes []*Route

	// Authenticator is the Authenticator to use to authenticate the requests.
	Authenticator Authenticator

	// Authorizer is the Authorizer to use to authorize the requests.
	Authorizer Authorizer

	// TLSRootCAPool is the *x509.CertPool to use for the secure bahamut api server.
	//
	// This is optional. Bahamut will use the system ca certs pool if possible,
	// or an empty one.
	TLSRootCAPool *x509.CertPool

	// TLSClientCAPool is the *x509.CertPool to use for the authentifying client.
	//
	// If given, mutual tls authentication will be possible, and the behavior will
	// depends on the value of TLSAuthType.
	TLSClientCAPool *x509.CertPool

	// TLSServerCertificates are the TLS certficates to use for the secure api server.
	//
	// This is optional. If you don't provide it, then Bahamut will start
	// without TLS support.
	TLSServerCertificates []tls.Certificate

	// TLSAuthType defines the tls authentication mode to use for a secure
	// api server.
	TLSAuthType tls.ClientAuthType

	// Disabled defines if the API system should be enabled.
	Disabled bool

	// ReadTimeout defines the read http timeout.
	ReadTimeout time.Duration

	// WriteTimeout defines the write http timeout.
	WriteTimeout time.Duration

	// WriteTimeout defines the idle http timeout.
	IdleTimeout time.Duration
}

// A PushServerConfig contains the configuration for the Bahamut Push Server.
type PushServerConfig struct {

	// Service defines the pubsub service to user.
	Service PubSubServer

	// Topic defines the default notification topic to use.
	Topic string

	// SessionsHandler defines the handler that will be used to
	// manage push session lifecycle.
	SessionsHandler PushSessionsHandler

	// Authenticator is the Authenticator to use to authenticate the requests.
	Authenticator Authenticator

	// Authorizer is the Authorizer to use to authorize the requests.
	Authorizer Authorizer

	// IdentifiablesFactory is a function that returns a instance of a model
	// according to its identity.
	IdentifiablesFactory func(identity string) elemental.Identifiable

	// Disabled defines if the Push system should be enabled.
	Disabled bool
}
