[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.1"

[[constraint]]
  name = "github.com/nats-io/nats-server"
  version = "1.4.1"