name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.23"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: setup
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: build
        run: |
          make

      #- uses: PaloAltoNetworks/cov@3.2.0
      #  with:
      #    main_branch: master
      #    cov_file: unit_coverage.out
      #    cov_threshold: "90"
      #    cov_mode: coverage
