name: build-go
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash

env:
  GO111MODULE: on

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.17
          - 1.16
          - 1.15
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: setup-for-old-go
        if: ${{ matrix.go < 1.17 }}
        run: |
          # stay on an old version of golangci-lint which still reports properly
          #
          # see release notes and this file for detail:
          # https://github.com/golangci/golangci-lint/blob/v1.43.0/.github/workflows/pr.yml#L67-70
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1

      - name: setup-for-current-go
        if: ${{ matrix.go >= 1.17 }}
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: setup
        run: |
          go version
          go get github.com/securego/gosec/cmd/gosec
          #go get golang.org/x/tools/cmd/cover
          go get github.com/axw/gocov/gocov
          go get github.com/AlekSi/gocov-xml

      - name: build
        run: |
          make

      # note: uncertain how gracefully this handles the matrix
      - name: coverage
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}

          # a comma-separated list
          coverage-reports: "./coverage.xml"
